# -*- coding: utf-8 -*-
"""ML project_4057

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1auYBB-Zk3zGFsfpZUucM5PltK6AfeAUH

**HT:2403A54057**

**LOAD THE DATASET**
"""

import pandas as pd

df = pd.read_csv('/content/laptop_prices (1) (1).csv')

print("First 5 rows of the dataset:")
display(df.head())

"""**DATA UNDERSTANDING**"""

# Identify categorical columns for one-hot encoding (excluding high cardinality ones like 'Product', 'CPU_model', 'GPU_model')
categorical_cols = [
    'Company',
    'TypeName',
    'OS',
    'Screen',
    'Touchscreen',
    'IPSpanel',
    'RetinaDisplay',
    'CPU_company',
    'PrimaryStorageType',
    'SecondaryStorageType',
    'GPU_company'
]

# Apply one-hot encoding
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print("First 5 rows of the DataFrame after one-hot encoding:")
display(df_encoded.head())
print(f"\nShape of the DataFrame after one-hot encoding: {df_encoded.shape}")

# Identify categorical columns for one-hot encoding (excluding high cardinality ones like 'Product', 'CPU_model', 'GPU_model')
categorical_cols = [
    'Company',
    'TypeName',
    'OS',
    'Screen',
    'Touchscreen',
    'IPSpanel',
    'RetinaDisplay',
    'CPU_company',
    'PrimaryStorageType',
    'SecondaryStorageType',
    'GPU_company'
]

# Apply one-hot encoding
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print("First 5 rows of the DataFrame after one-hot encoding:")
display(df_encoded.head())
print(f"\nShape of the DataFrame after one-hot encoding: {df_encoded.shape}")

print("\nDataset Information:")
df.info()

print("\nDescriptive Statistics:")
display(df.describe(include='all'))

print("\nMissing Values:")
display(df.isnull().sum())

from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
# We'll use the one-hot encoded DataFrame df_encoded for features
# and 'Price_euros' as the target variable

X = df_encoded.drop('Price_euros', axis=1)
y = df_encoded['Price_euros']

# Split the data into training and testing sets (e.g., 80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

from sklearn.preprocessing import StandardScaler

# Identify numerical columns for scaling
# Exclude 'Product', 'CPU_model', 'GPU_model' as they are high-cardinality object types we haven't encoded yet
# Exclude one-hot encoded columns (they are binary and don't need scaling in the same way)

# Get numerical columns from X_train (excluding object type columns)
numerical_cols = X_train.select_dtypes(include=['int64', 'float64']).columns

# Initialize the StandardScaler
scaler = StandardScaler()

# Apply scaling to the numerical columns in X_train
X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])

# Apply scaling to the numerical columns in X_test using the SAME scaler fitted on X_train
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])

print("First 5 rows of X_train after standardization:")
display(X_train.head())

from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns # Import seaborn

# Initialize and train a RandomForestRegressor model
# Using random_state for reproducibility
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train.select_dtypes(include=np.number), y_train) # Fit only on numerical columns

# Get feature importances
feature_importances = model.feature_importances_

# Get feature names
feature_names = X_train.select_dtypes(include=np.number).columns

# Create a pandas Series for easy viewing and sorting
importance_df = pd.Series(feature_importances, index=feature_names).sort_values(ascending=False)

print("Top 15 Feature Importances:")
display(importance_df.head(15))

# Plotting feature importances
plt.figure(figsize=(12, 8))
sns.barplot(x=importance_df.head(15).values, y=importance_df.head(15).index)
plt.title('Top 15 Feature Importances from RandomForestRegressor')
plt.xlabel('Importance')
plt.ylabel('Feature Name')
plt.tight_layout()
plt.show()

print("\nX_train Data Types:")
X_train.info()

print("\nX_test Data Types:")
X_test.info()

# Drop the remaining object columns from X_train and X_test
high_cardinality_cols = ['Product', 'CPU_model', 'GPU_model']

X_train = X_train.drop(columns=high_cardinality_cols)
X_test = X_test.drop(columns=high_cardinality_cols)

print("\nX_train Data Types after dropping object columns:")
X_train.info()

print("\nX_test Data Types after dropping object columns:")
X_test.info()

from sklearn.ensemble import RandomForestRegressor

# Initialize the Random Forest Regressor model with a random state for reproducibility
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model using the training data
model.fit(X_train, y_train)

print("Random Forest Regressor model trained successfully!")

from sklearn.linear_model import LinearRegression

# Initialize the Linear Regression model
linear_model = LinearRegression()

# Train the model using the training data
linear_model.fit(X_train, y_train)

print("Linear Regression model trained successfully!")

from sklearn.tree import DecisionTreeRegressor

# Initialize the Decision Tree Regressor model
decision_tree_model = DecisionTreeRegressor(random_state=42)

# Train the model using the training data
decision_tree_model.fit(X_train, y_train)

print("Decision Tree Regressor model trained successfully!")

from sklearn.svm import SVR

# Initialize the Support Vector Regressor model
# Using a linear kernel for simplicity as a start, can be tuned later
svr_model = SVR(kernel='linear')

# Train the model using the training data
svr_model.fit(X_train, y_train)

print("Support Vector Regressor model trained successfully!")



from sklearn.neighbors import KNeighborsRegressor

# Initialize the K-Nearest Neighbors Regressor model
# Using n_neighbors=5 as a starting point, can be tuned later
knn_model = KNeighborsRegressor(n_neighbors=5)

# Train the model using the training data
knn_model.fit(X_train, y_train)

print("K-Nearest Neighbors Regressor model trained successfully!")

from sklearn.ensemble import GradientBoostingRegressor

# Initialize the Gradient Boosting Regressor model
gbr_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Train the model using the training data
gbr_model.fit(X_train, y_train)

print("Gradient Boosting Regressor model trained successfully!")

from sklearn.ensemble import AdaBoostRegressor

# Initialize the AdaBoost Regressor model
adaboost_model = AdaBoostRegressor(n_estimators=100, random_state=42)

# Train the model using the training data
adaboost_model.fit(X_train, y_train)

print("AdaBoost Regressor model trained successfully!")

import pandas as pd
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
import numpy as np

# --- Re-running necessary data loading and preprocessing steps to ensure X_train and y_train are defined ---

# Load the dataset (assuming it's in the same path as before)
df = pd.read_csv('/content/laptop_prices (1) (1).csv')

# Identify categorical columns for one-hot encoding (excluding high cardinality ones like 'Product', 'CPU_model', 'GPU_model')
categorical_cols = [
    'Company',
    'TypeName',
    'OS',
    'Screen',
    'Touchscreen',
    'IPSpanel',
    'RetinaDisplay',
    'CPU_company',
    'PrimaryStorageType',
    'SecondaryStorageType',
    'GPU_company'
]

# Apply one-hot encoding
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Define features (X) and target (y)
X = df_encoded.drop('Price_euros', axis=1)
y = df_encoded['Price_euros']

# Split the data into training and testing sets (e.g., 80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Identify numerical columns for scaling
numerical_cols = X_train.select_dtypes(include=['int64', 'float64']).columns

# Initialize the StandardScaler
scaler = StandardScaler()

# Apply scaling to the numerical columns in X_train
X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])

# Apply scaling to the numerical columns in X_test using the SAME scaler fitted on X_train
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])

# Drop the remaining object columns from X_train and X_test
high_cardinality_cols = ['Product', 'CPU_model', 'GPU_model']
X_train = X_train.drop(columns=high_cardinality_cols)
X_test = X_test.drop(columns=high_cardinality_cols)

# --- End of re-running preprocessing ---

# Initialize the Random Forest Regressor model with a random state for reproducibility
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model using the training data
model.fit(X_train, y_train)

# Define the number of folds for cross-validation
n_splits = 5
kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)

# Perform cross-validation on the Random Forest Regressor model
cv_scores = cross_val_score(model, X_train, y_train, cv=kf, scoring='neg_mean_squared_error')

# Convert negative MSE to positive RMSE for better interpretability
rmse_scores = np.sqrt(-cv_scores)

print(f"Cross-validation RMSE scores: {rmse_scores}")
print(f"Mean RMSE: {np.mean(rmse_scores):.2f}")
print(f"Standard deviation of RMSE: {np.std(rmse_scores):.2f}")

from sklearn.decomposition import PCA

# Initialize PCA to retain 95% of the variance
pca = PCA(n_components=0.95, random_state=42)

# Fit PCA on the training data and transform both training and test data
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

print(f"Original number of features: {X_train.shape[1]}")
print(f"Number of features after PCA (X_train): {X_train_pca.shape[1]}")
print(f"Shape of X_train_pca: {X_train_pca.shape}")
print(f"Shape of X_test_pca: {X_test_pca.shape}")

print(f"Variance explained by selected components: {pca.explained_variance_ratio_.sum():.2f}")

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor, AdaBoostRegressor
import pandas as pd
import numpy as np

# Dictionary to store models and their names
models = {
    'RandomForestRegressor': RandomForestRegressor(n_estimators=100, random_state=42),
    'LinearRegression': LinearRegression(),
    'DecisionTreeRegressor': DecisionTreeRegressor(random_state=42),
    'SVR': SVR(kernel='linear'),
    'KNeighborsRegressor': KNeighborsRegressor(n_neighbors=5),
    'GradientBoostingRegressor': GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42),
    'AdaBoostRegressor': AdaBoostRegressor(n_estimators=100, random_state=42)
}

# DataFrame to store results
results_pca = []

for name, model in models.items():
    print(f"Training {name}...")
    # Train the model on PCA-transformed data
    model.fit(X_train_pca, y_train)

    # Make predictions on PCA-transformed test data
    y_pred_pca = model.predict(X_test_pca)

    # Evaluate the model
    mae = mean_absolute_error(y_test, y_pred_pca)
    mse = mean_squared_error(y_test, y_pred_pca)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred_pca)

    results_pca.append({
        'Model': name,
        'MAE': mae,
        'MSE': mse,
        'RMSE': rmse,
        'R2 Score': r2
    })

# Convert results to a DataFrame
df_results_pca = pd.DataFrame(results_pca)

print("\nModel Comparison Results on PCA-transformed Data:")
display(df_results_pca.sort_values(by='RMSE'))

from sklearn.metrics import roc_curve, mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.decomposition import PCA # Import PCA
import numpy as np
import pandas as pd # Import pandas
from sklearn.model_selection import train_test_split # Import train_test_split
from sklearn.preprocessing import StandardScaler # Import StandardScaler

print("Attempting to calculate ROC curve for a regression problem...")

# --- Re-running necessary data loading and preprocessing steps to ensure X_train and y_train are defined ---

# Load the dataset (assuming it's in the same path as before)
df = pd.read_csv('/content/laptop_prices (1) (1).csv')

# Identify categorical columns for one-hot encoding (excluding high cardinality ones like 'Product', 'CPU_model', 'GPU_model')
categorical_cols = [
    'Company',
    'TypeName',
    'OS',
    'Screen',
    'Touchscreen',
    'IPSpanel',
    'RetinaDisplay',
    'CPU_company',
    'PrimaryStorageType',
    'SecondaryStorageType',
    'GPU_company'
]

# Apply one-hot encoding
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Define features (X) and target (y)
X = df_encoded.drop('Price_euros', axis=1)
y = df_encoded['Price_euros']

# Split the data into training and testing sets (e.g., 80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Identify numerical columns for scaling
numerical_cols = X_train.select_dtypes(include=['int64', 'float64']).columns

# Initialize the StandardScaler
scaler = StandardScaler()

# Apply scaling to the numerical columns in X_train
X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])

# Apply scaling to the numerical columns in X_test using the SAME scaler fitted on X_train
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])

# Drop the remaining object columns from X_train and X_test
high_cardinality_cols = ['Product', 'CPU_model', 'GPU_model']
X_train = X_train.drop(columns=high_cardinality_cols)
X_test = X_test.drop(columns=high_cardinality_cols)

# --- End of re-running preprocessing ---


# Redefine the models dictionary for this cell's scope
models = {
    'RandomForestRegressor': RandomForestRegressor(n_estimators=100, random_state=42),
    'LinearRegression': LinearRegression(),
    'DecisionTreeRegressor': DecisionTreeRegressor(random_state=42),
    'SVR': SVR(kernel='linear'),
    'KNeighborsRegressor': KNeighborsRegressor(n_neighbors=5),
    'GradientBoostingRegressor': GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42),
    'AdaBoostRegressor': AdaBoostRegressor(n_estimators=100, random_state=42)
}

# --- Re-apply PCA transformation to ensure X_train_pca and X_test_pca are defined in this scope ---
# Initialize PCA to retain 95% of the variance
pca = PCA(n_components=0.95, random_state=42)

# Fit PCA on the training data and transform both training and test data
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)
# --- End of PCA re-application ---


# To make predictions, models need to be fitted on PCA-transformed data
for name, model in models.items():
    model.fit(X_train_pca, y_train)


try:
    # Pick one model's predictions, e.g., RandomForestRegressor
    rf_model = models['RandomForestRegressor']
    y_pred_rf_pca = rf_model.predict(X_test_pca)

    # This will raise a ValueError because `y_true` must be binary
    fpr, tpr, thresholds = roc_curve(y_test, y_pred_rf_pca)
    print("ROC curve calculated successfully. (Note: This output is unexpected for regression data)")
except ValueError as e:
    print(f"\nCaught expected error: {e}")
    print("This error demonstrates that `roc_curve` requires binary labels (0 or 1) for `y_true` and `y_score`.")
    print("Since our target variable `Price_euros` is continuous, ROC curves are not appropriate for evaluating these regression models.")


print("\nInstead of ROC curves, for regression, we focus on metrics like MAE, MSE, RMSE, and R2 score.")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

# --- Data Loading and Preprocessing Steps (Copied from earlier cells for self-containment) ---
# Load the dataset
df = pd.read_csv('/content/laptop_prices (1) (1).csv')

# Identify categorical columns for one-hot encoding
categorical_cols = [
    'Company', 'TypeName', 'OS', 'Screen', 'Touchscreen', 'IPSpanel',
    'RetinaDisplay', 'CPU_company', 'PrimaryStorageType', 'SecondaryStorageType',
    'GPU_company'
]

# Apply one-hot encoding
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Define features (X) and target (y)
X = df_encoded.drop('Price_euros', axis=1)
y = df_encoded['Price_euros']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Identify numerical columns for scaling
numerical_cols = X_train.select_dtypes(include=['int64', 'float64']).columns

# Initialize and apply StandardScaler
scaler = StandardScaler()
X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])

# Drop high-cardinality object columns
high_cardinality_cols = ['Product', 'CPU_model', 'GPU_model']
X_train = X_train.drop(columns=high_cardinality_cols)
X_test = X_test.drop(columns=high_cardinality_cols)

# --- PCA Transformation (Copied from earlier cells for self-containment) ---
pca = PCA(n_components=0.95, random_state=42)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

# --- Model Training and Evaluation ---
# Dictionary to store models and their names
models = {
    'RandomForestRegressor': RandomForestRegressor(n_estimators=100, random_state=42),
    'LinearRegression': LinearRegression(),
    'DecisionTreeRegressor': DecisionTreeRegressor(random_state=42),
    'SVR': SVR(kernel='linear'),
    'KNeighborsRegressor': KNeighborsRegressor(n_neighbors=5),
    'GradientBoostingRegressor': GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42),
    'AdaBoostRegressor': AdaBoostRegressor(n_estimators=100, random_state=42)
}

# DataFrame to store results
results_pca = []

for name, model in models.items():
    print(f"Training {name}...")
    # Train the model on PCA-transformed data
    model.fit(X_train_pca, y_train)

    # Make predictions on PCA-transformed test data
    y_pred_pca = model.predict(X_test_pca)

    # Evaluate the model
    mae = mean_absolute_error(y_test, y_pred_pca)
    mse = mean_squared_error(y_test, y_pred_pca)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred_pca)

    results_pca.append({
        'Model': name,
        'MAE': mae,
        'MSE': mse,
        'RMSE': rmse,
        'R2 Score': r2
    })

# Convert results to a DataFrame
df_results_pca = pd.DataFrame(results_pca)

print("\nModel Comparison Results on PCA-transformed Data:")
display(df_results_pca.sort_values(by='RMSE'))

# Identify the best model based on RMSE
best_model = df_results_pca.loc[df_results_pca['RMSE'].idxmin()]

print("\n--- Best Model Selection ---")
print(f"The best model based on the lowest RMSE is: {best_model['Model']}")
print(f"RMSE: {best_model['RMSE']:.2f}")
print(f"R2 Score: {best_model['R2 Score']:.2f}")

print("\n--- Justification ---")
print(f"The {best_model['Model']} demonstrated the lowest Root Mean Squared Error (RMSE) of {best_model['RMSE']:.2f} ")
print("on the test set with PCA-transformed features. RMSE is a critical metric for regression models, ")
print("as it indicates the average magnitude of the errors. A lower RMSE implies that the model's ")
print("predictions are closer to the actual values. Furthermore, it achieved the highest R2 score,")
print(f"which means it explains the most variance in the target variable (Price_euros) among all models tested.")
print("This suggests that the model is robust and provides the most accurate price predictions for laptops.")